#!/bin/bash

export LANG=C
CORPUS=$1

#----------------------------------------------------------------------
# read data corpus and prepared (stemmed) df file
#----------------------------------------------------------------------
zcat $CORPUS.tgz \
    | ./tar /dev/stdin \
    | sort -k3 > $CORPUS.concordance 2> dofast.stderr

mv df $CORPUS.df

cat -n $CORPUS.df \
    | join -13 -23 - $CORPUS.concordance \
    | sort -k4,4 -k2,2n > $CORPUS.tfdf

N=`cat N`
echo N $N

../dotfidfinline $N < $CORPUS.tfdf > $CORPUS.svm.fil
