#!/bin/bash

export LANG=C
TOPIC=$2
CORPUS=$3

find $1 -type f -exec ./dosteminline {} \; \
    | sort -k3 > $TOPIC/concordance.$1

cat -n $CORPUS.df \
    | join -13 -23 - $TOPIC/concordance.$1 \
    | sort -k4,4 -k2,2n > $TOPIC/tfdf.$1.sort

N=`cat N`
echo N $N

./dotfidfinline $N < $TOPIC/tfdf.$1.sort > $TOPIC/svm.$1.fil
