#!/bin/bash

#===============================================================================
#       USAGE:  ./preprocess <judgeclass> <verbose> <topic> <query>
#
# DESCRIPTION: Creates and loads start up files, creates seed trainsets.
#===============================================================================

source "${ABS_PATH}/handle_errors"
source "${ABS_PATH}/colors"

JUDGECLASS=$1; shift
VERBOSE=false; [[ $1 == "true" ]] && VERBOSE=true; shift
TOPIC=$1; shift
QUERY=$1; shift

function check_file {
    if [ `wc -l < $1` -eq 0 ]; then
            $VERBOSE && e_secondary "Error FILE $1 EQUAL TO ZERO"
            break;
    fi
}


RESULT_DIR="result/${JUDGECLASS}"

$VERBOSE && e_primary "Creating directories to store results..."

try
(
    rm -rf "${RESULT_DIR}/${TOPIC}/"
    mkdir -p "${RESULT_DIR}/${TOPIC}/"

) 2> $STD_ERROR_OUT

catch || {
    exit_on_error
}

$VERBOSE && e_success "Done."


$VERBOSE && e_primary "Creating topic directory..."

try
(
    rm -rf $TOPIC
    mkdir $TOPIC
    cp -r SSARP $TOPIC/

) 2> $STD_ERROR_OUT

catch || {
    exit_on_error
}


$VERBOSE && e_success "Done."

$VERBOSE && e_primary "Creating goldendb.$TOPIC..."

# try
# (
cat judgement/qrels.$JUDGECLASS.list \
    | grep "$TOPIC " \
    | cut -d' ' -f3 \
    | sort > $TOPIC/goldendb.$TOPIC

#)
echo "Creating goldendb.$TOPIC with size `wc -l < $TOPIC/goldendb.$TOPIC`"
$VERBOSE && e_primary "Creating goldendb.$TOPIC with size `wc -l < $TOPIC/goldendb.$TOPIC`"
# 2> $STD_ERROR_OUT
# 
# catch || {
#     exit_on_error
# }


$VERBOSE && e_success "Done."


#----------------------------------------------------------------------
# if data is already prepared, skips data extraction
#----------------------------------------------------------------------
if [ ! -f "${JUDGECLASS}.svm.fil" ]; then
    pushd Corpus

    e_primary "Preparing dataset (executing dofast)..."
    ./dofast "$JUDGECLASS" $VERBOSE
    e_success "Done."

    cp "$JUDGECLASS".df ../"$JUDGECLASS".df > /dev/null

    cp "$JUDGECLASS".svm.fil ../"$JUDGECLASS".svm.fil

      
    #rm "$JUDGECLASS".svm.fil.svd
     
    popd
fi



if [ ! -f "${TOPIC}.svm.fil" ]; then
    pushd Corpus
    
    python3 script_create_pids.py $TOPIC
    mv $TOPIC.svm.fil ../$TOPIC/
    e_primary "svm fil file with `wc -l < ../$TOPIC/$TOPIC.svm.fil` docs"
    
#     e_primary "Preparing dataset (executing dofast)..."
#     ./dofast "$JUDGECLASS" $VERBOSE
#     e_success "Done."
# 
#     cp "$JUDGECLASS".df ../"$JUDGECLASS".df > /dev/null
# 
#     cp "$JUDGECLASS".svm.fil ../"$JUDGECLASS".svm.fil

      
    #rm "$JUDGECLASS".svm.fil.svd
     
    popd
fi




pushd Corpus

echo "$QUERY" > "$TOPIC".seed.doc
cp $TOPIC.seed.doc ../$TOPIC.seed.doc

e_primary "bm25 seed selection `echo $QUERY` $TOPIC ..."
mkdir obj
tar -cvzf seed.$TOPIC.tgz "$TOPIC".seed.doc

zcat seed.$TOPIC.tgz | ./tar /dev/stdin  |  cut -d' ' -f3 > PorterSeed.$TOPIC 2> /dev/null  


# try
# (   

   python3 bm25.py ${JUDGECLASS} "$TOPIC".seed.doc ../$TOPIC/goldendb.$TOPIC $TOPIC

# ) 2> $STD_ERROR_OUT
# 
# catch || {
#     exit_on_error
# }
popd

e_success "Done."


# $VERBOSE && e_primary "Set the total number of docs relevants..."
# 
# try
# (
#     echo `wc -l < "$JUDGECLASS".svm.fil` > N
# 
# ) 2> $STD_ERROR_OUT
# 
# catch || {
#     exit_on_error
# }

$VERBOSE && e_success "Done."

pushd $TOPIC



ln -n ../$JUDGECLASS.svm.fil $JUDGECLASS.svm.fil

$VERBOSE && echo "Preparing 'docfils' file with all documents..."

try
(
    cut -d' ' -f1 $TOPIC.svm.fil \
        | sed -e 's/.*/& &/' > docfil

    cut -d' ' -f1 docfil \
        | cat -n > docfils

) 2> $STD_ERROR_OUT

catch || {
    exit_on_error
}

$VERBOSE && e_success "Done."

$VERBOSE && echo "Preparing auxiliary and result files..."

try
(
    touch rel.$TOPIC.fil
    touch prel.$TOPIC

    rm -rf prevalence.rate
    touch prevalence.rate

    rm -rf rel.rate
    touch rel.rate

    rm -f new[0-9][0-9].$TOPIC tail[0-9][0-9].$TOPIC self*.$TOPIC gold*.$TOPIC
    touch new00.$TOPIC

) 2> $STD_ERROR_OUT

catch || {
    exit_on_error
}

$VERBOSE && e_success "Done."

popd

$VERBOSE && e_primary "Executing ./dofeaturesseed..."
./dofeaturesseed $TOPIC.seed.doc $TOPIC $JUDGECLASS $VERBOSE
$VERBOSE && e_success "Finished ./dofeaturesseed."

pushd $TOPIC

# TODO: Adds error detection here.
$VERBOSE && e_primary "Preparing ../$TOPIC.svm.fil (runs ../dosplit)..."

sed -e 's/[^ ]*/0/' $TOPIC.svm.fil \
    | ../dosplit

$VERBOSE && e_success "Done."

$VERBOSE && e_primary "Preparing $TOPIC.synthetic.seed..."

try
(
    sed -e 's/[^ ]*/1/' svm.$TOPIC.seed.doc.fil > $TOPIC.synthetic.seed

) 2> $STD_ERROR_OUT

catch || {
    exit_on_error
}

$VERBOSE && e_success "Done."


rm ../${TOPIC}.svm.fil.svd
if [ ! -f "../${TOPIC}.svm.fil.svd" ]; then
    $VERBOSE && e_primary "Running feature compression SVD..."  
#     try
#     ( 

#   cat $TOPIC.synthetic.seed > seed.short.$TOPIC
    #cat $TOPIC.synthetic.seed >>   $TOPIC.svm.fil
    ../svd/./script_create_svd.sh  $TOPIC.svm.fil $TOPIC.synthetic.seed 10 $TOPIC
    #mv ../svd/$TOPIC.svm.fil.svd .
    
    tail -n 1 $TOPIC.svm.fil.svd > $TOPIC.synthetic.seed.svd  
    
    sort -k 1 $TOPIC.svm.fil.svd > temp 
    mv temp $TOPIC.svm.fil.svd
    cp $TOPIC.svm.fil.svd ../
    sed -i -e 's/^/0 /' $TOPIC.synthetic.seed.svd  
    
    head -n -1 $TOPIC.svm.fil.svd > temp.txt ; mv temp.txt $TOPIC.svm.fil.svd
    
     $VERBOSE && e_secondary "New svd file size is  `wc -l < $TOPIC.svm.fil.svd`..."   
   
#     ) 2> $STD_ERROR_OUT
# 
#     catch || {
#         exit_on_error
#     }  
else 
    #just copy the file 
    $VERBOSE && e_primary "copy  SVD file ..."
    sort -k 1 ../${TOPIC}.svm.fil.svd > ${TOPIC}.svm.fil.svd
    #cp "../${JUDGECLASS}.svm.fil.svd" .
fi

check_file $TOPIC.svm.fil.svd

$VERBOSE && e_success "Done."

#-------------------------------------------------------------------------
# set kissdb parameters and execute it if database doesn't exists
#-------------------------------------------------------------------------
KEYSIZE=$(awk 'BEGIN{a=0}{len = length($1); a=a<len?len:a}END{print a}' \
    $TOPIC.svm.fil)
VALSIZE=$(awk 'BEGIN{a=0}{len = length($0); a=a<len?len:a}END{print a}' \
    $TOPIC.svm.fil)
KEYSIZE=$((KEYSIZE+2))
VALSIZE=$((VALSIZE+2))

rm $TOPIC.db

if [ ! -f "$TOPIC.db" ]; then
    $VERBOSE && e_primary "Indexing $TOPIC, keysize = $KEYSIZE, valsize = $VALSIZE"

    try
    (
        ../indexer $TOPIC.svm.fil "$TOPIC".db $KEYSIZE $VALSIZE

    ) 2> $STD_ERROR_OUT

    catch || {
        exit_on_error
    }

    $VERBOSE && e_success "Done."
fi

popd
