#!/bin/bash


TOPICNUMBER=0
rm saida.*
for i in `seq 0 $TOPICNUMBER`; do 
    rm -r tr`echo $i`
    echo "running $i"
    #./main -c MedicalDB  -t tr`echo $i` -v -o --off-colors &> saida.$i &
    ./main -c MedicalDB  -s 7  -t tr`echo $i` -v -o --off-colors &>> saida.$i &
   # ./main -c athome1mu4x7  -t athome10`echo $i` -v -o --off-colors -s 10 &>> saida.$i &
     sleep 120
done
wait

